homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.405384
  longitude: 2.806917
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  
  customize_glob:
    "sensor.seventeentrack_package_*":
      icon: mdi:truck
  

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml

frontend:
  themes: !include_dir_merge_named themes/
  
input_number: !include_dir_merge_named input_number/  

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - 350720595
      
notify:
  - name: telegram_notif
    platform: telegram
    chat_id: 350720595

http: !include conf_dir/http.yaml
#  api_password: !secret http_password
  
    
alexa: !include alexa.yaml
  

hacs:
  token: !secret hacs_token
# Discover some devices automatically
discovery:
# Sensors
sensor: !include_dir_merge_list sensors/

alert: !include alert.yaml
  
binary_sensor: !include_dir_merge_list binary_sensors/
  
weather: !include_dir_list weather/
# Text to speech
tts: !include texttospeech.yaml

group: !include groups.yaml

automation: !include_dir_merge_list automation/

script: !include_dir_merge_list scripts/

speedtestdotnet: !include conf_dir/speedtest.yaml

timer:
  flash:
    duration: '00:00:05'
  zigbee_permit_join:
    name: Time remaining
    duration: 600 

media_player: !include media_player.yaml

panel_iframe:
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: https://192.168.1.8:4865
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://192.168.1.8:8321
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: https://home.piquette.fr/tasmoadmin
    #url: https://192.168.1.8:9541
  phlex:
    title: Phlex
    icon: mdi:microphone
    url: https://home.piquette.fr:1778

mqtt: !include mqtt.yaml

readme:

recorder:
  db_url: !secret db_mysql

device_tracker: !include_dir_merge_list device_tracker/

breaking_changes:

light: !include_dir_merge_list lights/

scene: !include_dir_list /config/scenes

shell_command:
  stop_openvpn: 'sh /config/openvpn_stop.sh'
  restart_openvpn: 'sh /config/openvpn_restart.sh'

variable:  
  last_motion:
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Derni√®re Ouverture"

input_boolean: !include_dir_merge_named input_boulean/
  
zone:
  - name: Travail
    latitude: 49.2731476
    longitude: 2.5039287
    radius: 200
    icon: mdi:briefcase

google_assistant: !include conf_dir/google_assistant.yaml
  
switch: !include_dir_merge_list switchs/

# transmission:
#   host: https://piquette.fr/transmission
#   #port: 443
#   username: !secret user_transmission
#   password: !secret password_transmission



      
